spring:
  flyway:
    locations: classpath:db/migration,classpath:db/migration/dev
  mail:
    host: localhost
    port: 1025
    username: ''
    password: ''
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

app:
  cors:
    allowed-origins: "http://localhost:*"
  ip-check:
    enabled: false
